name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:
    name : Build container
    runs-on: ubuntu-latest

    steps:
    - name : Checkout
      uses: actions/checkout@v3

    - name : Login to Docker Hub 
      uses : docker/login-action@v1
      with :
        username : ${{secrets.USERNAME_DOCKER_HUB}}
        password : ${{secrets.ACCESS_TOKEN_DOCKER_HUB}}

    - name: Build and push to Docker Hub
      uses : docker/build-push-action@v2
      with:
        context : .
        push: true
        tags : abishaefrei/tp1devops:0.0.1

